blog/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("post/<slug:title>/", views.post, name="post"),
    path("category/<str:name>/", views.category, name="category"),
    path("search/", views.search, name="search"),
    path("create-post/", views.create_post, name="create_post"),
    path("login/", LoginView.as_view(), name="blog_login"),
    path("logout/", views.custom_logout, name="blog_logout"),
    path("register/", views.register_view, name="register"),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<int:id><slug:slug>/", views.product_detail, name="product_detail"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
]

website/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('', include('helloweb.urls')),
                  path('', include('blog.urls')),
                  path('gallery/', include('gallery.urls')),
                  path('shop/', include('shop.urls', namespace='shop')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('order/', include('order.urls', namespace='order')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name="Назва")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"


class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name="Тег")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"


class Post(models.Model):
    title = models.CharField(max_length=30, verbose_name="Заголовок")
    content = models.TextField(verbose_name="Опис")
    published_date = models.DateTimeField(auto_created=True, verbose_name="Дата та час публікації")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категорія")
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name="Автор")
    image = models.URLField(default="https://fraserbond.com/oc-content/plugins/blog/img/blog/blog-default.png")
    tags = models.ManyToManyField(Tag, verbose_name="Теги")
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Новина"
        verbose_name_plural = "Новини"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments", verbose_name="Пост")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор")
    content = models.TextField(verbose_name="Коментар")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата коментаря")

    def __str__(self):
        return f"Коментар від {self.user.username} до {self.post.title}"

    class Meta:
        verbose_name = "Коментар"
        verbose_name_plural = "Коментарі"

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('published_date', 'user')


class RegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email", required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "POST"
        self.helper.add_input(Submit("submit", "Зареєструватися"))

blog/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.timezone import now

from .models import Post, Category
from .forms import PostForm, RegisterForm


def get_categories():
    all = Category.objects.all()
    count = all.count()
    half = count / 2
    return {'cats1': all[:half], 'cats2': all[half:]}


def index(request):
    posts = Post.objects.all().order_by('-published_date')
    # posts = Post.objects.filter(title__contains='django1')
    # posts = Post.objects.filter(published_date__year=2025)
    # posts = Post.objects.filter(published_date__month=1, published_date__year=2024)
    # posts = Post.objects.filter(category__name__exact="django")
    context = {'posts': posts}
    context.update(get_categories())
    return render(request, "blog/index.html", context)


def post(request, title):
    post = get_object_or_404(Post, slug=title)
    context = {'post': post}
    context.update(get_categories())
    return render(request, "blog/post.html", context)


def category(request, name):
    c = get_object_or_404(Category, name=name)
    posts = Post.objects.filter(category=c).order_by('-published_date')
    context = {'posts': posts}
    context.update(get_categories())
    return render(request, "blog/index.html", context)


def search(request):
    query = request.GET.get('query')
    posts = Post.objects.filter(Q(content__icontains=query) | Q(title__icontains=query))
    context = {'posts': posts}
    context.update(get_categories())
    return render(request, "blog/index.html", context)


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.published_date = now()
            post.user = request.user
            post.save()
            return index(request)
    create_form = PostForm()
    context = {'create_form': create_form}
    context.update(get_categories())
    return render(request, "blog/create.html", context)


def custom_logout(request):
    logout(request)
    return redirect('index')


def register_view(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("index")
    else:
        form = RegisterForm()
    context = {"form": form}
    context.update(get_categories())
    return render(request, "blog/register.html", context)

templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href=" {% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'blog/css/blog-home.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
{% include 'blog/nav.html' with active_page='index' %}
<!-- Page Content -->
<div class="container">

    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">
            {% block content %} {% endblock %}
        </div>

        <!-- Blog Sidebar Widgets Column -->
        <div class="col-md-4">

           {% block sidebar %} {% endblock %}
        </div>
    <!-- /.row -->

    <hr>

    {% include 'blog/footer.html' %}

</div>
<!-- /.container -->

<!-- jQuery -->
<script src="{% static 'blog/js/jquery.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>

</body>

</html>

templates/blog/create.html
{% extends "blog/base.html" %}


{% block content %}
<h1 class="page-header">Create new post</h1>

<form method="POST" action="{% url 'create_post' %}">
  {% csrf_token %}
  {% load crispy_forms_tags %}
  {{ create_form | crispy }}
  <input type="submit" value="save" class="btn btn-primary">
</form>
{% endblock %}

templates/blog/footer.html
<!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2025</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
<h1 class="page-header">
    Page Heading
    <small>Secondary Text</small>
</h1>
{% for post in posts %}
    <h2>
        <a href="{% url 'post' title=post.slug %}">{{ post.title }}</a>
    </h2>
    <p class="lead">
        by <a href="index.php">{{ post.user }}</a>
    </p>
    <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.published_date }}</p>
    <hr>
    <img class="img-responsive" src="{{ post.image }}" alt="">
    <hr>
    <p>{{ post.content|truncatewords:20 }}</p>
    <a class="btn btn-primary" href="{% url 'post' title=post.slug %}">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
    <hr>
{% empty %}
<p>Немає постів!</p>
{% endfor %}
<!-- Pager -->
<ul class="pager">
    <li class="previous">
        <a href="#">&larr; Older</a>
    </li>
    <li class="next">
        <a href="#">Newer &rarr;</a>
    </li>
</ul>
{% endblock %}

{% block sidebar %}
{%include 'blog/sidebar.html' %}
{% endblock %}

templates/blog/login.html
{% if user.is_authenticated %}
<div class="navbar-form navbar-right">
    <a href="#">Hello, {{user}}</a>
    <a href="{% url 'blog_logout' %}" class="btn btn-danger">Logout</a>
</div>
{% else %}
<form action="{% url 'blog_login' %}" method="POST" class="navbar-form navbar-right">
    {% csrf_token %}
    <input type="text" placeholder="Login" name="username" class="form-control">
    <input type="password" placeholder="password" name="password" class="form-control">
    <input type="submit" class="btn btn-primary" value="Sign in">
     <a href="{% url 'register' %}" class="btn btn-success">Sign up</a>
</form>
{% endif %}

templates/blog/nav.html
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">Blog</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <li class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    {% if active_page|default:"index" == "index" %}
                    <a href="{% url 'index' %}" class="active">Home</a>
                    {% else %}
                    <a href="{% url 'index' %}">Home</a>
                    {% endif %}
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
                <li>
                    <a href="{% url 'shop:product_list' %}">Shop</a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'create_post' %}">Create post</a>
                </li>
                {% endif %}

                <li>
                    {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                        <a href="{% url 'cart:cart_detail' %}">Your cart: {{ total_items }} ${{ cart.get_total_price }}</a>
                        {% else %}
                        <p>Your cart is empty</p>
                        {% endif %}
                    {% endwith %}
                </li>
            </ul>
            {% include 'blog/login.html' %}

    </div>
    <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

templates/blog/post.html
{% extends "blog/base.html" %}

{% block content %}

                <!-- Blog Post -->

                <!-- Title -->
                <h1>{{ post.title }}</h1>

                <!-- Author -->
                <p class="lead">
                    by <a href="#">{{ post.user }}</a>
                </p>

                <hr>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.published_date}}</p>

                <hr>

                <!-- Preview Image -->
                <img class="img-responsive" src="{{ post.image }}" alt="">

                <hr>

                <!-- Post Content -->
                <p class="lead">{{ post.content }}</p>

                <hr>

                <!-- Blog Comments -->

                <!-- Comments Form -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form">
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        <!-- Nested Comment -->
                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object" src="http://placehold.it/64x64" alt="">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">Nested Start Bootstrap
                                    <small>August 25, 2014 at 9:30 PM</small>
                                </h4>
                                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                            </div>
                        </div>
                        <!-- End Nested Comment -->
                    </div>
                </div>

{% endblock %}

templates/blog/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="">
    <h2>Реєстрація</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Зареєструватися</button>
    </form>
</div>
{% endblock %}

templates/blog/sidebar.html

            <!-- Blog Search Well -->
            <div class="well">
                <h4>Blog Search</h4>
                <form action="{% url 'search' %}" method="GET" class="input-group">
                    <input type="search" name="query" class="form-control">
                    <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                </form>
                <!-- /.input-group -->
            </div>

            <!-- Blog Categories Well -->
            <div class="well">
                <h4>Blog Categories</h4>
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            {% for cat in cats1 %}
                            <li><a href="{% url 'category' name=cat.name %}">{{ cat }}</a></li>
                          {% endfor %}
                        </ul>
                    </div>
                    <!-- /.col-lg-6 -->
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            {% for cat in cats2 %}
                            <li><a href="{% url 'category' name=cat.name %}">{{ cat }}</a>
                            </li>
                          {% endfor %}
                        </ul>
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
            </div>

            <!-- Side Widget Well -->
            <div class="well">
                <h4>Side Widget Well</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus
                    laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
            </div>

        </div>